In [7]:
import numpy as np

In [8]:
kanto = np.array([73, 67, 43])

In [9]:
weights = np.array([0.3, 0.2, 0.5])

In [10]:
np.dot(kanto, weights)

56.8

In [11]:
(kanto * weights).sum()

56.8

In [12]:
weights.shape

(3,)

## 3-D Array

In [13]:
array_3d = np.array([
    [
        [1,2,3], [4,5, 6]
    ],
    [
        [7,8, 9], [10, 11, 12]
    ],
    [
        [13,14, 15], [16, 17, 18]
    ]
])

In [14]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [15]:
array_3d.shape

(3, 2, 3)

In [16]:
array_3d.dtype

dtype('int64')

In [17]:
np.dot(array_3d, weights)

array([[ 2.2,  5.2],
       [ 8.2, 11.2],
       [14.2, 17.2]])

## MATRIX MULTIPLICATION

#### climate_data = np.array([temperature, rainfall, humidity])

In [18]:
climate_data = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70],
])

In [19]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [20]:
climate_data.shape

(5, 3)

In [21]:
weights

array([0.3, 0.2, 0.5])

##### Matrix Multiplication

In [22]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

##### Matrix Multiplication - Another Method

In [23]:
climate_results = climate_data @ weights

In [24]:
climate_results

array([56.8, 76.9, 81.9, 57.7, 74.9])

##### Reshape Data

In [25]:
climate_results.reshape(climate_results.shape[0], 1)

array([[56.8],
       [76.9],
       [81.9],
       [57.7],
       [74.9]])

In [26]:
#np.concatenate & np.savetxt

## Numpy Arithmetic Operation

In [27]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [28]:
arr2 = np.array([
    [11,12,13],
    [14,15,16]
])

#### Array Addition

In [29]:
np.add(arr1, arr2)

array([[12, 14, 16],
       [18, 20, 22]])

In [30]:
arr1 + arr2

array([[12, 14, 16],
       [18, 20, 22]])

#### Array Subtraction

In [31]:
np.subtract(arr2, arr1)

array([[10, 10, 10],
       [10, 10, 10]])

In [32]:
arr2 - arr1

array([[10, 10, 10],
       [10, 10, 10]])

#### Array Multiplication

In [33]:
np.multiply(arr1, arr2)

array([[11, 24, 39],
       [56, 75, 96]])

In [34]:
arr1 * arr2

array([[11, 24, 39],
       [56, 75, 96]])

#### Array Division

In [35]:
np.divide(arr1, 2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [36]:
arr1 / 2 

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

#### Array Mode

In [37]:
np.mod(arr1,2)

array([[1, 0, 1],
       [0, 1, 0]])

In [38]:
arr1 % 2

array([[1, 0, 1],
       [0, 1, 0]])

#### Array Power

In [39]:
np.power(arr1, 2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [40]:
arr1 ** 2 

array([[ 1,  4,  9],
       [16, 25, 36]])

## Numpy Array Broadcasting

In [41]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [42]:
arr2 = np.array([
    [11,12,13]
])

#### When we try to add arr1 + arr2, before doing this numpy replicate arr2 from np.array([ [11,12,13] ]) to np.array([ [11,12,13], [11,12,13] ]). This is called array broadcasting. Broadcasting only works if one of the arrays can be replicated to exactly match the shape of the other array.

In [43]:
arr1 + arr2

array([[12, 14, 16],
       [15, 17, 19]])

## Array Comparison

In [44]:
arr1 = np.array([
    [1,2,3], [4,5,6],
])

In [45]:
arr2 = np.array([
    [1,2,4], [8,9,6]
])

In [46]:
arr1 == arr2

array([[ True,  True, False],
       [False, False,  True]])

In [47]:
arr1 != arr2

array([[False, False,  True],
       [ True,  True, False]])

In [48]:
arr1 >= arr2

array([[ True,  True, False],
       [False, False,  True]])

#### Below code consider True as 1 and False as 0

In [49]:
(arr1 == arr2).sum()

3

## Array Indexing and Slicing

In [50]:
arr1 = np.array([
    [[1,2,3], [4,5,6]],
    [[4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15]]
])

In [51]:
arr1.shape

(3, 2, 3)

In [52]:
# Array Indexing
arr1[2,1,1]

14

In [53]:
# SubArray using ranges
arr1[1:,0:1,:2]

array([[[ 4,  5]],

       [[10, 11]]])

In [54]:
arr1[1:,0:1,:2].shape

(2, 1, 2)

## Special Arrays

In [55]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.random.rand()

0.033207631341799715

In [59]:
# This is used to generate an array with random value between 0 & 1
np.random.rand(4,3)

array([[0.85693601, 0.3148668 , 0.84099272],
       [0.21469668, 0.55239351, 0.07876426],
       [0.95601428, 0.95234629, 0.20443898],
       [0.14372088, 0.7215838 , 0.20136555]])

##### This is used to generate an array with random value between 0 & 1

In [60]:
np.random.randn()

1.0801096597462259

In [61]:
# This function is used to create an array with random values close to zero. This function may return positive or negative number as well
np.random.randn(5,4)

array([[ 0.20438048, -1.46760188,  0.25986714,  0.61649321],
       [ 2.00457189, -0.631456  ,  1.71673482,  0.33678584],
       [-0.21037156, -0.12624396, -2.83079242,  0.32522408],
       [ 1.12539434, -0.53394953,  0.59383682,  0.94580879],
       [ 0.69873233,  1.33901505,  0.10338117,  0.03681785]])

#### This function is used to create an array with random values close to zero. This function may return positive or negative number as well

In [62]:
np.random.randint(1,8)

1

In [63]:
np.random.randint(1,8,7)

array([7, 4, 6, 3, 3, 5, 7])

#### This function is used to create an array with random values between given range

In [64]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [65]:
# Array Reshape
np.arange(10, 90, 3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])