## NumPy

#### NumPy is a Python library for numerical computations and is often used for tasks involving arrays, matrices and mathematical operation

##### $ pip install numpy

In [1]:
import numpy as np

In [2]:
kanto = np.array([73, 67, 43])

In [3]:
weights = np.array([0.3, 0.2, 0.5])

##### Array dimensions

In [4]:
weights.shape

(3,)

##### Data Type of array elements

In [5]:
weights.dtype

dtype('float64')

##### Number of array dimensions

In [6]:
weights.ndim

1

##### Total number of elements

In [7]:
weights.size

3

### Dot Product

In [8]:
np.dot(kanto, weights)

56.8

In [9]:
(kanto * weights).sum()

56.8

### 3-D Array

In [10]:
array_3d = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8]],
        [
            [9, 10, 11, 12],
            [13, 14, 15, 16],
        ],
        [[17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)

In [11]:
array_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [12]:
# Array dimensions
array_3d.shape

(3, 2, 4)

In [13]:
# Data type of the array elements
array_3d.dtype

dtype('int64')

In [14]:
# Number of array dimensions
array_3d.ndim

3

In [15]:
# Total number of elements
array_3d.size

24

##### Reshaping Arrays

In [16]:
array_3d.reshape(8, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

##### Transpose an Array

In [17]:
array_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [18]:
array_3d.T

array([[[ 1,  9, 17],
        [ 5, 13, 21]],

       [[ 2, 10, 18],
        [ 6, 14, 22]],

       [[ 3, 11, 19],
        [ 7, 15, 23]],

       [[ 4, 12, 20],
        [ 8, 16, 24]]])

### MATRIX MULTIPLICATION

#### climate_data = np.array([temperature, rainfall, humidity])

In [19]:
climate_data = np.array(
    [
        [73, 67, 43],
        [91, 88, 64],
        [87, 134, 58],
        [102, 43, 37],
        [69, 96, 70],
    ]
)

In [20]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [21]:
climate_data.shape

(5, 3)

In [22]:
weights

array([0.3, 0.2, 0.5])

##### Matrix Multiplication

In [23]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

##### Matrix Multiplication - Another Method

In [24]:
climate_results = climate_data @ weights

In [25]:
climate_results

array([56.8, 76.9, 81.9, 57.7, 74.9])

##### Reshape Data

In [26]:
climate_results.reshape(climate_results.shape[0], 1)

array([[56.8],
       [76.9],
       [81.9],
       [57.7],
       [74.9]])

In [27]:
#np.concatenate & np.savetxt

### Numpy Arithmetic Operation

In [28]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [29]:
arr2 = np.array([[11, 12, 13], [14, 15, 16]])

#### Array Addition

In [30]:
np.add(arr1, arr2)

array([[12, 14, 16],
       [18, 20, 22]])

In [31]:
arr1 + arr2

array([[12, 14, 16],
       [18, 20, 22]])

#### Array Subtraction

In [32]:
np.subtract(arr2, arr1)

array([[10, 10, 10],
       [10, 10, 10]])

In [33]:
arr2 - arr1

array([[10, 10, 10],
       [10, 10, 10]])

#### Array Multiplication

In [34]:
np.multiply(arr1, arr2)

array([[11, 24, 39],
       [56, 75, 96]])

In [35]:
arr1 * arr2

array([[11, 24, 39],
       [56, 75, 96]])

#### Array Division

In [36]:
np.divide(arr1, 2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [37]:
arr1 / 2 

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

#### Array Mode

In [38]:
np.mod(arr1, 2)

array([[1, 0, 1],
       [0, 1, 0]])

In [39]:
arr1 % 2

array([[1, 0, 1],
       [0, 1, 0]])

#### Array Power

In [40]:
np.power(arr1, 2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [41]:
arr1 ** 2 

array([[ 1,  4,  9],
       [16, 25, 36]])

### Numpy Array Broadcasting

In [42]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [43]:
arr2 = np.array([[11, 12, 13]])

##### When we try to add arr1 + arr2, before doing this numpy replicate arr2 from np.array([ [11,12,13] ]) to np.array([ [11,12,13], [11,12,13] ]). This is called array broadcasting. Broadcasting only works if one of the arrays can be replicated to exactly match the shape of the other array.

In [44]:
arr1 + arr2

array([[12, 14, 16],
       [15, 17, 19]])

### Array Comparison

In [45]:
arr1 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

In [46]:
arr2 = np.array([[1, 2, 4], [8, 9, 6]])

In [47]:
arr1 == arr2

array([[ True,  True, False],
       [False, False,  True]])

In [48]:
arr1 != arr2

array([[False, False,  True],
       [ True,  True, False]])

In [49]:
arr1 >= arr2

array([[ True,  True, False],
       [False, False,  True]])

##### Below code consider True as 1 and False as 0

In [50]:
(arr1 == arr2).sum()

3

### Array Indexing and Slicing

In [51]:
arr1 = np.array(
    [[[1, 2, 3], [4, 5, 6]], [[4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15]]]
)

In [52]:
arr1.shape

(3, 2, 3)

In [53]:
# Array Indexing
arr1[2, 1, 1]

14

In [54]:
# SubArray using ranges
arr1[1:, 0:1, :2]

array([[[ 4,  5]],

       [[10, 11]]])

In [55]:
arr1[1:, 0:1, :2].shape

(2, 1, 2)

### Special Arrays

In [56]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Numpy Random function

In [59]:
np.random.rand()

0.8858350564009478

In [60]:
# This is used to generate an array with random value between 0 & 1
np.random.rand(4, 3)

array([[0.95205756, 0.45851965, 0.80815536],
       [0.18311757, 0.78507094, 0.16585512],
       [0.57248367, 0.79349226, 0.62596731],
       [0.69292044, 0.82657388, 0.91363945]])

##### This is used to generate an array with random value between 0 & 1

In [61]:
np.random.randn()

-1.6440799762263185

In [62]:
# This function is used to create an array with random values close to zero. This function may return positive or negative number as well
np.random.randn(5, 4)

array([[ 0.27708564, -1.21310495,  1.24287879,  0.27908293],
       [-0.64674666,  1.07641896,  0.20629141, -0.43775499],
       [ 1.3113496 ,  0.92402299, -1.70525285, -0.13869388],
       [-0.75974367, -0.49578072,  0.64047189,  0.14064987],
       [-0.18892718,  1.06611648, -1.80631823, -1.99072368]])

##### This function is used to create an array with random values close to zero. This function may return positive or negative number as well

In [63]:
np.random.randint(1, 4)

1

In [64]:
np.random.randint(1, 9, 8)

array([4, 4, 8, 5, 5, 1, 3, 3])

#### This function is used to create an array with random values between given range

##### Random Choice

In [65]:
np.random.choice(["Product A", "Product B", "Product C"])

'Product A'

In [66]:
np.random.choice(["Product A", "Product B", "Product C"], 10)

array(['Product A', 'Product B', 'Product B', 'Product A', 'Product C',
       'Product A', 'Product B', 'Product A', 'Product B', 'Product A'],
      dtype='<U9')

### Numpy Range function

In [67]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [68]:
# Array Reshape
np.arange(10, 90, 3).reshape(3, 3, 3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

### Numpy Arithmetic functions

In [69]:
x = np.arange(10, 90, 3)

In [70]:
y = np.arange(20, 100, 4).reshape(5, 2, 2)

In [71]:
y

array([[[20, 24],
        [28, 32]],

       [[36, 40],
        [44, 48]],

       [[52, 56],
        [60, 64]],

       [[68, 72],
        [76, 80]],

       [[84, 88],
        [92, 96]]])

In [72]:
np.max(x)

88

In [73]:
np.max(y)

96

In [74]:
np.min(x)

10

In [75]:
np.min(y)

20

In [76]:
np.argmax(y)

19

In [77]:
np.argmin(y)

0

In [78]:
np.sin(y)

array([[[ 0.91294525, -0.90557836],
        [ 0.27090579,  0.55142668]],

       [[-0.99177885,  0.74511316],
        [ 0.01770193, -0.76825466]],

       [[ 0.98662759, -0.521551  ],
        [-0.30481062,  0.92002604]],

       [[-0.89792768,  0.25382336],
        [ 0.56610764, -0.99388865]],

       [[ 0.73319032,  0.0353983 ],
        [-0.77946607,  0.98358775]]])

In [79]:
np.cos(x)

array([-0.83907153,  0.90744678, -0.95765948,  0.98870462, -0.99996083,
        0.99120281, -0.96260587,  0.91474236, -0.84857027,  0.76541405,
       -0.66693806,  0.5551133 , -0.43217794,  0.30059254, -0.16299078,
        0.02212676,  0.11918014, -0.25810164,  0.39185723, -0.5177698 ,
        0.6333192 , -0.73619272,  0.82433133, -0.89597095,  0.9496777 ,
       -0.98437664,  0.99937328])

In [80]:
np.tan(y)

array([[[ 2.23716094, -2.1348967 ],
        [-0.2814296 ,  0.66100604]],

       [[ 7.75047091, -1.11721493],
        [ 0.0177047 ,  1.20012724]],

       [[-6.05327238, -0.61127369],
        [ 0.32004039,  2.34786031]],

       [[-2.0400816 , -0.26241738],
        [ 0.68674769,  9.00365495]],

       [[-1.07818381,  0.0354205 ],
        [ 1.24427006, -5.45134011]]])

In [81]:
np.cumsum(x)

array([  10,   23,   39,   58,   80,  105,  133,  164,  198,  235,  275,
        318,  364,  413,  465,  520,  578,  639,  703,  770,  840,  913,
        989, 1068, 1150, 1235, 1323])

In [82]:
y

array([[[20, 24],
        [28, 32]],

       [[36, 40],
        [44, 48]],

       [[52, 56],
        [60, 64]],

       [[68, 72],
        [76, 80]],

       [[84, 88],
        [92, 96]]])

In [83]:
np.cumsum(x)

array([  10,   23,   39,   58,   80,  105,  133,  164,  198,  235,  275,
        318,  364,  413,  465,  520,  578,  639,  703,  770,  840,  913,
        989, 1068, 1150, 1235, 1323])

In [84]:
np.sqrt(x)

array([3.16227766, 3.60555128, 4.        , 4.35889894, 4.69041576,
       5.        , 5.29150262, 5.56776436, 5.83095189, 6.08276253,
       6.32455532, 6.55743852, 6.78232998, 7.        , 7.21110255,
       7.41619849, 7.61577311, 7.81024968, 8.        , 8.18535277,
       8.36660027, 8.54400375, 8.71779789, 8.88819442, 9.05538514,
       9.21954446, 9.38083152])

In [85]:
np.sqrt(y)

array([[[4.47213595, 4.89897949],
        [5.29150262, 5.65685425]],

       [[6.        , 6.32455532],
        [6.63324958, 6.92820323]],

       [[7.21110255, 7.48331477],
        [7.74596669, 8.        ]],

       [[8.24621125, 8.48528137],
        [8.71779789, 8.94427191]],

       [[9.16515139, 9.38083152],
        [9.59166305, 9.79795897]]])

In [86]:
np.mean(y)

58.0

### Linear Algebra

In [87]:
y

array([[[20, 24],
        [28, 32]],

       [[36, 40],
        [44, 48]],

       [[52, 56],
        [60, 64]],

       [[68, 72],
        [76, 80]],

       [[84, 88],
        [92, 96]]])

##### Inverse of a matrix

In [88]:
np.linalg.inv(y)

array([[[-1.   ,  0.75 ],
        [ 0.875, -0.625]],

       [[-1.5  ,  1.25 ],
        [ 1.375, -1.125]],

       [[-2.   ,  1.75 ],
        [ 1.875, -1.625]],

       [[-2.5  ,  2.25 ],
        [ 2.375, -2.125]],

       [[-3.   ,  2.75 ],
        [ 2.875, -2.625]]])

##### Determinant of a matrix

In [89]:
np.linalg.det(y)

array([-32., -32., -32., -32., -32.])

In [90]:
# System of equations:
# 3x + 1y = 9
# 1x + 2y = 8

A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])

solution = np.linalg.solve(A, B)
print(solution)

[2. 3.]
