## NumPy

#### NumPy is a Python library for numerical computations and is often used for tasks involving arrays, matrices and mathematical operation

##### $ pip install numpy

In [ ]:
import numpy as np

In [ ]:
kanto = np.array([73, 67, 43])

In [ ]:
weights = np.array([0.3, 0.2, 0.5])

In [ ]:
weights.shape

(3,)

### Dot Product

In [ ]:
np.dot(kanto, weights)

56.8

In [ ]:
(kanto * weights).sum()

56.8

### 3-D Array

In [ ]:
array_3d = np.array([
    [
        [1, 2, 3, 4], [5, 6, 7, 8]
    ],
    [
        [9, 10, 11, 12], [13,14, 15, 16],
    ],
    [
        [17, 18, 19, 20], [21, 22, 23, 24]
    ]
])

In [ ]:
array_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
array_3d.shape

(3, 2, 4)

In [ ]:
array_3d.dtype

dtype('int64')

### MATRIX MULTIPLICATION

#### climate_data = np.array([temperature, rainfall, humidity])

In [ ]:
climate_data = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70],
])

In [ ]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
climate_data.shape

(5, 3)

In [ ]:
weights

array([0.3, 0.2, 0.5])

##### Matrix Multiplication

In [ ]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

##### Matrix Multiplication - Another Method

In [ ]:
climate_results = climate_data @ weights

In [ ]:
climate_results

array([56.8, 76.9, 81.9, 57.7, 74.9])

##### Reshape Data

In [ ]:
climate_results.reshape(climate_results.shape[0], 1)

array([[56.8],
       [76.9],
       [81.9],
       [57.7],
       [74.9]])

In [ ]:
#np.concatenate & np.savetxt

### Numpy Arithmetic Operation

In [ ]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
arr2 = np.array([
    [11,12,13],
    [14,15,16]
])

#### Array Addition

In [ ]:
np.add(arr1, arr2)

array([[12, 14, 16],
       [18, 20, 22]])

In [ ]:
arr1 + arr2

array([[12, 14, 16],
       [18, 20, 22]])

#### Array Subtraction

In [ ]:
np.subtract(arr2, arr1)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
arr2 - arr1

array([[10, 10, 10],
       [10, 10, 10]])

#### Array Multiplication

In [ ]:
np.multiply(arr1, arr2)

array([[11, 24, 39],
       [56, 75, 96]])

In [ ]:
arr1 * arr2

array([[11, 24, 39],
       [56, 75, 96]])

#### Array Division

In [ ]:
np.divide(arr1, 2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [ ]:
arr1 / 2 

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

#### Array Mode

In [ ]:
np.mod(arr1,2)

array([[1, 0, 1],
       [0, 1, 0]])

In [ ]:
arr1 % 2

array([[1, 0, 1],
       [0, 1, 0]])

#### Array Power

In [ ]:
np.power(arr1, 2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arr1 ** 2 

array([[ 1,  4,  9],
       [16, 25, 36]])

### Numpy Array Broadcasting

In [ ]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
arr2 = np.array([
    [11,12,13]
])

##### When we try to add arr1 + arr2, before doing this numpy replicate arr2 from np.array([ [11,12,13] ]) to np.array([ [11,12,13], [11,12,13] ]). This is called array broadcasting. Broadcasting only works if one of the arrays can be replicated to exactly match the shape of the other array.

In [ ]:
arr1 + arr2

array([[12, 14, 16],
       [15, 17, 19]])

### Array Comparison

In [ ]:
arr1 = np.array([
    [1,2,3], [4,5,6],
])

In [ ]:
arr2 = np.array([
    [1,2,4], [8,9,6]
])

In [ ]:
arr1 == arr2

array([[ True,  True, False],
       [False, False,  True]])

In [ ]:
arr1 != arr2

array([[False, False,  True],
       [ True,  True, False]])

In [ ]:
arr1 >= arr2

array([[ True,  True, False],
       [False, False,  True]])

##### Below code consider True as 1 and False as 0

In [ ]:
(arr1 == arr2).sum()

3

### Array Indexing and Slicing

In [ ]:
arr1 = np.array([
    [[1,2,3], [4,5,6]],
    [[4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15]]
])

In [ ]:
arr1.shape

(3, 2, 3)

In [ ]:
# Array Indexing
arr1[2,1,1]

14

In [ ]:
# SubArray using ranges
arr1[1:,0:1,:2]

array([[[ 4,  5]],

       [[10, 11]]])

In [ ]:
arr1[1:,0:1,:2].shape

(2, 1, 2)

### Special Arrays

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Numpy Random function

In [ ]:
np.random.rand()

0.24562064660596727

In [ ]:
# This is used to generate an array with random value between 0 & 1
np.random.rand(4,3)

array([[0.66776063, 0.60682596, 0.24875443],
       [0.69249825, 0.21927041, 0.41062127],
       [0.76231221, 0.29225301, 0.71453811],
       [0.63834222, 0.66201616, 0.84354904]])

##### This is used to generate an array with random value between 0 & 1

In [ ]:
np.random.randn()

0.40029287626463733

In [ ]:
# This function is used to create an array with random values close to zero. This function may return positive or negative number as well
np.random.randn(5,4)

array([[ 0.3344239 ,  0.48875289, -0.59805447,  1.70916311],
       [ 0.00286524, -0.36583841, -0.10960816, -0.37905876],
       [ 0.99203659,  0.62632557, -0.20337062,  0.63400296],
       [ 0.59216779, -2.02057522,  0.17840096,  0.55581768],
       [-0.47058547, -0.06464062,  0.7901201 ,  0.43319521]])

##### This function is used to create an array with random values close to zero. This function may return positive or negative number as well

In [ ]:
np.random.randint(1,4)

1

In [ ]:
np.random.randint(1,9,8)

array([2, 3, 4, 5, 6, 3, 5, 7])

#### This function is used to create an array with random values between given range

##### Random Choice

In [ ]:
np.random.choice(['Product A', 'Product B', 'Product C'])

'Product C'

In [ ]:
np.random.choice(['Product A', 'Product B', 'Product C'], 10)

array(['Product C', 'Product A', 'Product A', 'Product A', 'Product A',
       'Product A', 'Product B', 'Product C', 'Product C', 'Product C'],
      dtype='<U9')

### Numpy Range function

In [ ]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [ ]:
# Array Reshape
np.arange(10, 90, 3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

### Numpy Arithmetic functions

In [ ]:
x = np.arange(10, 90, 3)

In [ ]:
y = np.arange(20, 100, 4).reshape(5, 2, 2)

In [ ]:
y

array([[[20, 24],
        [28, 32]],

       [[36, 40],
        [44, 48]],

       [[52, 56],
        [60, 64]],

       [[68, 72],
        [76, 80]],

       [[84, 88],
        [92, 96]]])

In [ ]:
np.max(x)

88

In [ ]:
np.max(y)

96

In [ ]:
np.min(x)

10

In [ ]:
np.min(y)

20

In [ ]:
np.argmax(y)

19

In [ ]:
np.argmin(y)

0

In [ ]:
np.sin(y)

array([[[ 0.91294525, -0.90557836],
        [ 0.27090579,  0.55142668]],

       [[-0.99177885,  0.74511316],
        [ 0.01770193, -0.76825466]],

       [[ 0.98662759, -0.521551  ],
        [-0.30481062,  0.92002604]],

       [[-0.89792768,  0.25382336],
        [ 0.56610764, -0.99388865]],

       [[ 0.73319032,  0.0353983 ],
        [-0.77946607,  0.98358775]]])

In [ ]:
np.cos(x)

array([-0.83907153,  0.90744678, -0.95765948,  0.98870462, -0.99996083,
        0.99120281, -0.96260587,  0.91474236, -0.84857027,  0.76541405,
       -0.66693806,  0.5551133 , -0.43217794,  0.30059254, -0.16299078,
        0.02212676,  0.11918014, -0.25810164,  0.39185723, -0.5177698 ,
        0.6333192 , -0.73619272,  0.82433133, -0.89597095,  0.9496777 ,
       -0.98437664,  0.99937328])

In [ ]:
np.tan(y)

array([[[ 2.23716094, -2.1348967 ],
        [-0.2814296 ,  0.66100604]],

       [[ 7.75047091, -1.11721493],
        [ 0.0177047 ,  1.20012724]],

       [[-6.05327238, -0.61127369],
        [ 0.32004039,  2.34786031]],

       [[-2.0400816 , -0.26241738],
        [ 0.68674769,  9.00365495]],

       [[-1.07818381,  0.0354205 ],
        [ 1.24427006, -5.45134011]]])

In [ ]:
np.cumsum(x)

array([  10,   23,   39,   58,   80,  105,  133,  164,  198,  235,  275,
        318,  364,  413,  465,  520,  578,  639,  703,  770,  840,  913,
        989, 1068, 1150, 1235, 1323])

In [ ]:
y

array([[[20, 24],
        [28, 32]],

       [[36, 40],
        [44, 48]],

       [[52, 56],
        [60, 64]],

       [[68, 72],
        [76, 80]],

       [[84, 88],
        [92, 96]]])

In [ ]:
np.cumsum(x)

array([  10,   23,   39,   58,   80,  105,  133,  164,  198,  235,  275,
        318,  364,  413,  465,  520,  578,  639,  703,  770,  840,  913,
        989, 1068, 1150, 1235, 1323])

In [ ]:
np.sqrt(x)

array([3.16227766, 3.60555128, 4.        , 4.35889894, 4.69041576,
       5.        , 5.29150262, 5.56776436, 5.83095189, 6.08276253,
       6.32455532, 6.55743852, 6.78232998, 7.        , 7.21110255,
       7.41619849, 7.61577311, 7.81024968, 8.        , 8.18535277,
       8.36660027, 8.54400375, 8.71779789, 8.88819442, 9.05538514,
       9.21954446, 9.38083152])

In [ ]:
np.sqrt(y)

array([[[4.47213595, 4.89897949],
        [5.29150262, 5.65685425]],

       [[6.        , 6.32455532],
        [6.63324958, 6.92820323]],

       [[7.21110255, 7.48331477],
        [7.74596669, 8.        ]],

       [[8.24621125, 8.48528137],
        [8.71779789, 8.94427191]],

       [[9.16515139, 9.38083152],
        [9.59166305, 9.79795897]]])