In [18]:
import numpy as np

In [19]:
kanto = np.array([73, 67, 43])

In [20]:
weights = np.array([0.3, 0.2, 0.5])

In [21]:
weights.shape

(3,)

## Dot Product

In [22]:
np.dot(kanto, weights)

56.8

In [23]:
(kanto * weights).sum()

56.8

## 3-D Array

In [24]:
array_3d = np.array([
    [
        [1, 2, 3, 4], [5, 6, 7, 8]
    ],
    [
        [9, 10, 11, 12], [13,14, 15, 16],
    ],
    [
        [17, 18, 19, 20], [21, 22, 23, 24]
    ]
])

In [25]:
array_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [26]:
array_3d.shape

(3, 2, 4)

In [27]:
array_3d.dtype

dtype('int64')

## MATRIX MULTIPLICATION

#### climate_data = np.array([temperature, rainfall, humidity])

In [28]:
climate_data = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70],
])

In [29]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [30]:
climate_data.shape

(5, 3)

In [31]:
weights

array([0.3, 0.2, 0.5])

##### Matrix Multiplication

In [32]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

##### Matrix Multiplication - Another Method

In [33]:
climate_results = climate_data @ weights

In [34]:
climate_results

array([56.8, 76.9, 81.9, 57.7, 74.9])

##### Reshape Data

In [35]:
climate_results.reshape(climate_results.shape[0], 1)

array([[56.8],
       [76.9],
       [81.9],
       [57.7],
       [74.9]])

In [36]:
#np.concatenate & np.savetxt

## Numpy Arithmetic Operation

In [37]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [38]:
arr2 = np.array([
    [11,12,13],
    [14,15,16]
])

#### Array Addition

In [39]:
np.add(arr1, arr2)

array([[12, 14, 16],
       [18, 20, 22]])

In [40]:
arr1 + arr2

array([[12, 14, 16],
       [18, 20, 22]])

#### Array Subtraction

In [41]:
np.subtract(arr2, arr1)

array([[10, 10, 10],
       [10, 10, 10]])

In [42]:
arr2 - arr1

array([[10, 10, 10],
       [10, 10, 10]])

#### Array Multiplication

In [43]:
np.multiply(arr1, arr2)

array([[11, 24, 39],
       [56, 75, 96]])

In [44]:
arr1 * arr2

array([[11, 24, 39],
       [56, 75, 96]])

#### Array Division

In [45]:
np.divide(arr1, 2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [46]:
arr1 / 2 

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

#### Array Mode

In [47]:
np.mod(arr1,2)

array([[1, 0, 1],
       [0, 1, 0]])

In [48]:
arr1 % 2

array([[1, 0, 1],
       [0, 1, 0]])

#### Array Power

In [49]:
np.power(arr1, 2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [50]:
arr1 ** 2 

array([[ 1,  4,  9],
       [16, 25, 36]])

## Numpy Array Broadcasting

In [51]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [52]:
arr2 = np.array([
    [11,12,13]
])

#### When we try to add arr1 + arr2, before doing this numpy replicate arr2 from np.array([ [11,12,13] ]) to np.array([ [11,12,13], [11,12,13] ]). This is called array broadcasting. Broadcasting only works if one of the arrays can be replicated to exactly match the shape of the other array.

In [53]:
arr1 + arr2

array([[12, 14, 16],
       [15, 17, 19]])

## Array Comparison

In [54]:
arr1 = np.array([
    [1,2,3], [4,5,6],
])

In [55]:
arr2 = np.array([
    [1,2,4], [8,9,6]
])

In [56]:
arr1 == arr2

array([[ True,  True, False],
       [False, False,  True]])

In [57]:
arr1 != arr2

array([[False, False,  True],
       [ True,  True, False]])

In [58]:
arr1 >= arr2

array([[ True,  True, False],
       [False, False,  True]])

#### Below code consider True as 1 and False as 0

In [59]:
(arr1 == arr2).sum()

3

## Array Indexing and Slicing

In [60]:
arr1 = np.array([
    [[1,2,3], [4,5,6]],
    [[4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15]]
])

In [61]:
arr1.shape

(3, 2, 3)

In [62]:
# Array Indexing
arr1[2,1,1]

14

In [63]:
# SubArray using ranges
arr1[1:,0:1,:2]

array([[[ 4,  5]],

       [[10, 11]]])

In [64]:
arr1[1:,0:1,:2].shape

(2, 1, 2)

## Special Arrays

In [65]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [66]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Numpy Random function

In [68]:
np.random.rand()

0.5053720357240583

In [69]:
# This is used to generate an array with random value between 0 & 1
np.random.rand(4,3)

array([[0.5152408 , 0.44047024, 0.10593025],
       [0.04315603, 0.57386147, 0.1227848 ],
       [0.25330148, 0.06796611, 0.62242061],
       [0.71932189, 0.87586349, 0.33830628]])

##### This is used to generate an array with random value between 0 & 1

In [70]:
np.random.randn()

-0.3938250799590138

In [71]:
# This function is used to create an array with random values close to zero. This function may return positive or negative number as well
np.random.randn(5,4)

array([[-0.15219163, -0.49015822, -0.53777798,  0.77406897],
       [ 0.52356779,  0.31609372,  0.74386736, -1.10128333],
       [ 0.883102  , -0.82400748, -0.14948619,  0.70139484],
       [-0.17665348, -0.31842521,  0.40575041, -0.77894677],
       [ 0.05929493, -0.63694255, -0.76974523, -0.5749799 ]])

##### This function is used to create an array with random values close to zero. This function may return positive or negative number as well

In [72]:
np.random.randint(1,8)

1

In [73]:
np.random.randint(1,8,7)

array([5, 6, 6, 3, 1, 5, 2])

#### This function is used to create an array with random values between given range

## Numpy Range function

In [98]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [97]:
# Array Reshape
np.arange(10, 90, 3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

## Numpy Arithmetic functions

In [95]:
x = np.arange(10, 90, 3)

In [132]:
y = np.arange(20, 100, 4).reshape(5, 2, 2)

In [133]:
y

array([[[20, 24],
        [28, 32]],

       [[36, 40],
        [44, 48]],

       [[52, 56],
        [60, 64]],

       [[68, 72],
        [76, 80]],

       [[84, 88],
        [92, 96]]])

In [121]:
np.max(x)

88

In [134]:
np.max(y)

96

In [135]:
np.min(x)

10

In [136]:
np.min(y)

20

In [137]:
np.argmax(y)

19

In [138]:
np.argmin(y)

0

In [140]:
np.sin(y)

array([[[ 0.91294525, -0.90557836],
        [ 0.27090579,  0.55142668]],

       [[-0.99177885,  0.74511316],
        [ 0.01770193, -0.76825466]],

       [[ 0.98662759, -0.521551  ],
        [-0.30481062,  0.92002604]],

       [[-0.89792768,  0.25382336],
        [ 0.56610764, -0.99388865]],

       [[ 0.73319032,  0.0353983 ],
        [-0.77946607,  0.98358775]]])

In [141]:
np.cos(x)

array([-0.83907153,  0.90744678, -0.95765948,  0.98870462, -0.99996083,
        0.99120281, -0.96260587,  0.91474236, -0.84857027,  0.76541405,
       -0.66693806,  0.5551133 , -0.43217794,  0.30059254, -0.16299078,
        0.02212676,  0.11918014, -0.25810164,  0.39185723, -0.5177698 ,
        0.6333192 , -0.73619272,  0.82433133, -0.89597095,  0.9496777 ,
       -0.98437664,  0.99937328])

In [142]:
np.tan(y)

array([[[ 2.23716094, -2.1348967 ],
        [-0.2814296 ,  0.66100604]],

       [[ 7.75047091, -1.11721493],
        [ 0.0177047 ,  1.20012724]],

       [[-6.05327238, -0.61127369],
        [ 0.32004039,  2.34786031]],

       [[-2.0400816 , -0.26241738],
        [ 0.68674769,  9.00365495]],

       [[-1.07818381,  0.0354205 ],
        [ 1.24427006, -5.45134011]]])